2023-10-11 19:18:37  (rev 0)
    +_libgcc_mutex-0.1 (defaults/linux-64)
    +_openmp_mutex-5.1 (defaults/linux-64)
    +bzip2-1.0.8 (defaults/linux-64)
    +ca-certificates-2023.08.22 (defaults/linux-64)
    +click-8.0.4 (defaults/linux-64)
    +flask-2.2.2 (defaults/linux-64)
    +itsdangerous-2.0.1 (defaults/noarch)
    +jinja2-3.1.2 (defaults/linux-64)
    +ld_impl_linux-64-2.38 (defaults/linux-64)
    +libffi-3.4.4 (defaults/linux-64)
    +libgcc-ng-11.2.0 (defaults/linux-64)
    +libgomp-11.2.0 (defaults/linux-64)
    +libstdcxx-ng-11.2.0 (defaults/linux-64)
    +libuuid-1.41.5 (defaults/linux-64)
    +markupsafe-2.1.1 (defaults/linux-64)
    +ncurses-6.4 (defaults/linux-64)
    +openssl-3.0.11 (defaults/linux-64)
    +pip-23.2.1 (defaults/linux-64)
    +python-3.11.5 (defaults/linux-64)
    +readline-8.2 (defaults/linux-64)
    +setuptools-68.0.0 (defaults/linux-64)
    +sqlite-3.41.2 (defaults/linux-64)
    +tk-8.6.12 (defaults/linux-64)
    +tzdata-2023c (defaults/noarch)
    +werkzeug-2.2.3 (defaults/linux-64)
    +wheel-0.41.2 (defaults/linux-64)
    +xz-5.4.2 (defaults/linux-64)
    +zlib-1.2.13 (defaults/linux-64)

2023-10-11 19:19:21  (rev 1)
     ca-certificates  {2023.08.22 (defaults/linux-64) -> 2023.08.22 (anaconda/linux-64)}
     flask  {2.2.2 (defaults/linux-64) -> 2.2.2 (anaconda/linux-64)}
     openssl  {3.0.11 (defaults/linux-64) -> 3.0.11 (anaconda/linux-64)}

2023-10-11 21:17:10  (rev 2)
     ca-certificates  {2023.08.22 (anaconda/linux-64) -> 2023.7.22 (conda-forge/linux-64)}
    +aniso8601-9.0.1 (conda-forge/noarch)
    +flask-restful-0.3.10 (conda-forge/noarch)
    +python-dateutil-2.8.2 (conda-forge/noarch)
    +pytz-2023.3.post1 (conda-forge/noarch)
    +six-1.16.0 (conda-forge/noarch)

2023-10-11 21:28:03  (rev 3)
    +python-dotenv-1.0.0 (conda-forge/noarch)

2023-10-11 21:32:40  (rev 4)
    +flask_cors-3.0.10 (conda-forge/noarch)

2023-10-12 10:04:34  (rev 5)
     _libgcc_mutex  {0.1 (defaults/linux-64) -> 0.1 (conda-forge/linux-64)}
     _openmp_mutex  {5.1 (defaults/linux-64) -> 4.5 (conda-forge/linux-64)}
     libgcc-ng  {11.2.0 (defaults/linux-64) -> 13.2.0 (conda-forge/linux-64)}
     libstdcxx-ng  {11.2.0 (defaults/linux-64) -> 13.2.0 (conda-forge/linux-64)}
     openssl  {3.0.11 (anaconda/linux-64) -> 3.1.3 (conda-forge/linux-64)}
    -libgomp-11.2.0 (defaults/linux-64)
    +aiohttp-3.8.5 (defaults/linux-64)
    +aiosignal-1.3.1 (conda-forge/noarch)
    +anyio-3.7.1 (conda-forge/noarch)
    +appdirs-1.4.4 (conda-forge/noarch)
    +async-timeout-4.0.3 (conda-forge/noarch)
    +attrs-23.1.0 (conda-forge/noarch)
    +beautifulsoup4-4.12.2 (conda-forge/noarch)
    +brotli-1.1.0 (conda-forge/linux-64)
    +brotli-bin-1.1.0 (conda-forge/linux-64)
    +brotli-python-1.1.0 (conda-forge/linux-64)
    +cachetools-5.3.1 (conda-forge/noarch)
    +certifi-2023.7.22 (conda-forge/noarch)
    +cffi-1.16.0 (conda-forge/linux-64)
    +charset-normalizer-3.3.0 (conda-forge/noarch)
    +colorama-0.4.6 (conda-forge/noarch)
    +contourpy-1.1.1 (conda-forge/linux-64)
    +cryptography-41.0.4 (conda-forge/linux-64)
    +cycler-0.12.1 (conda-forge/noarch)
    +dataclasses-json-0.5.7 (conda-forge/noarch)
    +docker-pycreds-0.4.0 (conda-forge/noarch)
    +et_xmlfile-1.1.0 (conda-forge/noarch)
    +exceptiongroup-1.1.3 (conda-forge/noarch)
    +fonttools-4.43.1 (conda-forge/linux-64)
    +freetype-2.12.1 (defaults/linux-64)
    +frozenlist-1.4.0 (conda-forge/linux-64)
    +fsspec-2023.9.2 (conda-forge/noarch)
    +giflib-5.2.1 (conda-forge/linux-64)
    +gitdb-4.0.10 (conda-forge/noarch)
    +gitpython-3.1.37 (conda-forge/noarch)
    +google-api-core-2.12.0 (conda-forge/noarch)
    +google-auth-2.23.3 (conda-forge/noarch)
    +googleapis-common-protos-1.60.0 (conda-forge/noarch)
    +greenlet-3.0.0 (conda-forge/linux-64)
    +idna-3.4 (conda-forge/noarch)
    +joblib-1.3.2 (conda-forge/noarch)
    +jpeg-9e (conda-forge/linux-64)
    +jsonpatch-1.33 (conda-forge/noarch)
    +jsonpointer-2.4 (conda-forge/linux-64)
    +kiwisolver-1.4.5 (conda-forge/linux-64)
    +langchain-0.0.312 (conda-forge/noarch)
    +langsmith-0.0.43 (conda-forge/noarch)
    +lcms2-2.15 (conda-forge/linux-64)
    +lerc-3.0 (defaults/linux-64)
    +libblas-3.9.0 (conda-forge/linux-64)
    +libbrotlicommon-1.1.0 (conda-forge/linux-64)
    +libbrotlidec-1.1.0 (conda-forge/linux-64)
    +libbrotlienc-1.1.0 (conda-forge/linux-64)
    +libcblas-3.9.0 (conda-forge/linux-64)
    +libdeflate-1.17 (defaults/linux-64)
    +libgfortran-ng-13.2.0 (conda-forge/linux-64)
    +libgfortran5-13.2.0 (conda-forge/linux-64)
    +liblapack-3.9.0 (conda-forge/linux-64)
    +libopenblas-0.3.24 (conda-forge/linux-64)
    +libpng-1.6.39 (defaults/linux-64)
    +libprotobuf-3.20.3 (defaults/linux-64)
    +libtiff-4.5.1 (defaults/linux-64)
    +libwebp-1.3.2 (defaults/linux-64)
    +libwebp-base-1.3.2 (conda-forge/linux-64)
    +llama-index-0.8.42 (conda-forge/noarch)
    +llvm-openmp-14.0.6 (defaults/linux-64)
    +lz4-c-1.9.4 (conda-forge/linux-64)
    +marshmallow-3.20.1 (conda-forge/noarch)
    +marshmallow-enum-1.5.1 (conda-forge/noarch)
    +matplotlib-base-3.8.0 (conda-forge/linux-64)
    +multidict-6.0.4 (conda-forge/linux-64)
    +munkres-1.1.4 (conda-forge/noarch)
    +mypy_extensions-1.0.0 (conda-forge/noarch)
    +nest-asyncio-1.5.7 (conda-forge/noarch)
    +nltk-3.8.1 (conda-forge/noarch)
    +nomkl-1.0 (conda-forge/noarch)
    +numexpr-2.8.7 (conda-forge/linux-64)
    +numpy-1.26.0 (conda-forge/linux-64)
    +openai-0.28.1 (conda-forge/noarch)
    +openapi-schema-pydantic-1.2.4 (conda-forge/noarch)
    +openpyxl-3.1.2 (conda-forge/linux-64)
    +packaging-23.2 (conda-forge/noarch)
    +pandas-2.1.1 (conda-forge/linux-64)
    +pandas-stubs-2.1.1.230928 (conda-forge/noarch)
    +pathtools-0.1.2 (conda-forge/noarch)
    +pillow-9.4.0 (defaults/linux-64)
    +plotly-5.17.0 (conda-forge/noarch)
    +protobuf-3.20.3 (conda-forge/linux-64)
    +psutil-5.9.5 (conda-forge/linux-64)
    +pyasn1-0.5.0 (conda-forge/noarch)
    +pyasn1-modules-0.3.0 (conda-forge/noarch)
    +pycparser-2.21 (conda-forge/noarch)
    +pydantic-1.10.13 (conda-forge/linux-64)
    +pyopenssl-23.2.0 (conda-forge/noarch)
    +pyparsing-3.1.1 (conda-forge/noarch)
    +pysocks-1.7.1 (conda-forge/noarch)
    +python-tzdata-2023.3 (conda-forge/noarch)
    +python_abi-3.11 (conda-forge/linux-64)
    +pyu2f-0.1.5 (conda-forge/noarch)
    +pyyaml-6.0.1 (conda-forge/linux-64)
    +regex-2023.10.3 (conda-forge/linux-64)
    +requests-2.31.0 (conda-forge/noarch)
    +rsa-4.9 (conda-forge/noarch)
    +scikit-learn-1.3.1 (conda-forge/linux-64)
    +scipy-1.11.3 (conda-forge/linux-64)
    +sentry-sdk-1.32.0 (conda-forge/noarch)
    +setproctitle-1.3.3 (conda-forge/linux-64)
    +smmap-3.0.5 (conda-forge/noarch)
    +sniffio-1.3.0 (conda-forge/noarch)
    +soupsieve-2.5 (conda-forge/noarch)
    +sqlalchemy-2.0.21 (conda-forge/linux-64)
    +stringcase-1.2.0 (conda-forge/noarch)
    +tenacity-8.2.3 (conda-forge/noarch)
    +threadpoolctl-3.2.0 (conda-forge/noarch)
    +tiktoken-0.5.1 (conda-forge/linux-64)
    +tqdm-4.66.1 (conda-forge/noarch)
    +tree_sitter-0.20.2 (conda-forge/linux-64)
    +tree_sitter_languages-1.7.0 (conda-forge/linux-64)
    +types-pytz-2023.3.1.1 (conda-forge/noarch)
    +typing-extensions-4.8.0 (conda-forge/noarch)
    +typing_extensions-4.8.0 (conda-forge/noarch)
    +typing_inspect-0.9.0 (conda-forge/noarch)
    +urllib3-1.26.17 (conda-forge/noarch)
    +wandb-0.15.12 (conda-forge/noarch)
    +yaml-0.2.5 (conda-forge/linux-64)
    +yarl-1.9.2 (conda-forge/linux-64)
    +zstd-1.5.5 (defaults/linux-64)

2023-11-10 21:49:23  (rev 6)
     openssl  {3.1.3 (conda-forge/linux-64) -> 3.1.4 (conda-forge/linux-64)}
    +sseclient-0.0.27 (conda-forge/noarch)

2024-01-08 11:01:13  (rev 7)
     _openmp_mutex  {4.5 (conda-forge/linux-64) -> 4.5 (conda-forge/linux-64)}
     aiohttp  {3.8.5 (defaults/linux-64) -> 3.9.1 (conda-forge/linux-64)}
     attrs  {23.1.0 (conda-forge/noarch) -> 23.2.0 (conda-forge/noarch)}
     bzip2  {1.0.8 (defaults/linux-64) -> 1.0.8 (conda-forge/linux-64)}
     ca-certificates  {2023.7.22 (conda-forge/linux-64) -> 2023.11.17 (conda-forge/linux-64)}
     cachetools  {5.3.1 (conda-forge/noarch) -> 5.3.2 (conda-forge/noarch)}
     certifi  {2023.7.22 (conda-forge/noarch) -> 2023.11.17 (conda-forge/noarch)}
     charset-normalizer  {3.3.0 (conda-forge/noarch) -> 3.3.2 (conda-forge/noarch)}
     click  {8.0.4 (defaults/linux-64) -> 8.1.7 (conda-forge/noarch)}
     contourpy  {1.1.1 (conda-forge/linux-64) -> 1.2.0 (conda-forge/linux-64)}
     cryptography  {41.0.4 (conda-forge/linux-64) -> 41.0.7 (conda-forge/linux-64)}
     dataclasses-json  {0.5.7 (conda-forge/noarch) -> 0.6.3 (conda-forge/noarch)}
     exceptiongroup  {1.1.3 (conda-forge/noarch) -> 1.2.0 (conda-forge/noarch)}
     flask  {2.2.2 (anaconda/linux-64) -> 3.0.0 (conda-forge/noarch)}
     fonttools  {4.43.1 (conda-forge/linux-64) -> 4.47.0 (conda-forge/linux-64)}
     freetype  {2.12.1 (defaults/linux-64) -> 2.12.1 (conda-forge/linux-64)}
     frozenlist  {1.4.0 (conda-forge/linux-64) -> 1.4.1 (conda-forge/linux-64)}
     fsspec  {2023.9.2 (conda-forge/noarch) -> 2023.12.2 (conda-forge/noarch)}
     gitdb  {4.0.10 (conda-forge/noarch) -> 4.0.11 (conda-forge/noarch)}
     gitpython  {3.1.37 (conda-forge/noarch) -> 3.1.40 (conda-forge/noarch)}
     google-auth  {2.23.3 (conda-forge/noarch) -> 2.26.1 (conda-forge/noarch)}
     greenlet  {3.0.0 (conda-forge/linux-64) -> 3.0.3 (conda-forge/linux-64)}
     idna  {3.4 (conda-forge/noarch) -> 3.6 (conda-forge/noarch)}
     itsdangerous  {2.0.1 (defaults/noarch) -> 2.1.2 (conda-forge/noarch)}
     jinja2  {3.1.2 (defaults/linux-64) -> 3.1.2 (conda-forge/noarch)}
     lcms2  {2.15 (conda-forge/linux-64) -> 2.16 (conda-forge/linux-64)}
     ld_impl_linux-64  {2.38 (defaults/linux-64) -> 2.40 (conda-forge/linux-64)}
     lerc  {3.0 (defaults/linux-64) -> 4.0.0 (conda-forge/linux-64)}
     libblas  {3.9.0 (conda-forge/linux-64) -> 3.9.0 (conda-forge/linux-64)}
     libcblas  {3.9.0 (conda-forge/linux-64) -> 3.9.0 (conda-forge/linux-64)}
     libdeflate  {1.17 (defaults/linux-64) -> 1.19 (conda-forge/linux-64)}
     libffi  {3.4.4 (defaults/linux-64) -> 3.4.2 (conda-forge/linux-64)}
     libgcc-ng  {13.2.0 (conda-forge/linux-64) -> 13.2.0 (conda-forge/linux-64)}
     libgfortran-ng  {13.2.0 (conda-forge/linux-64) -> 13.2.0 (conda-forge/linux-64)}
     libgfortran5  {13.2.0 (conda-forge/linux-64) -> 13.2.0 (conda-forge/linux-64)}
     liblapack  {3.9.0 (conda-forge/linux-64) -> 3.9.0 (conda-forge/linux-64)}
     libopenblas  {0.3.24 (conda-forge/linux-64) -> 0.3.25 (conda-forge/linux-64)}
     libpng  {1.6.39 (defaults/linux-64) -> 1.6.39 (conda-forge/linux-64)}
     libprotobuf  {3.20.3 (defaults/linux-64) -> 4.24.4 (conda-forge/linux-64)}
     libstdcxx-ng  {13.2.0 (conda-forge/linux-64) -> 13.2.0 (conda-forge/linux-64)}
     libtiff  {4.5.1 (defaults/linux-64) -> 4.6.0 (conda-forge/linux-64)}
     libuuid  {1.41.5 (defaults/linux-64) -> 2.38.1 (conda-forge/linux-64)}
     markupsafe  {2.1.1 (defaults/linux-64) -> 2.1.3 (conda-forge/linux-64)}
     matplotlib-base  {3.8.0 (conda-forge/linux-64) -> 3.8.2 (conda-forge/linux-64)}
     ncurses  {6.4 (defaults/linux-64) -> 6.4 (conda-forge/linux-64)}
     nest-asyncio  {1.5.7 (conda-forge/noarch) -> 1.5.8 (conda-forge/noarch)}
     numexpr  {2.8.7 (conda-forge/linux-64) -> 2.8.8 (conda-forge/linux-64)}
     numpy  {1.26.0 (conda-forge/linux-64) -> 1.26.3 (conda-forge/linux-64)}
     openssl  {3.1.4 (conda-forge/linux-64) -> 3.2.0 (conda-forge/linux-64)}
     pandas  {2.1.1 (conda-forge/linux-64) -> 2.1.4 (conda-forge/linux-64)}
     pandas-stubs  {2.1.1.230928 (conda-forge/noarch) -> 2.1.4.231227 (conda-forge/noarch)}
     pillow  {9.4.0 (defaults/linux-64) -> 10.2.0 (conda-forge/linux-64)}
     pip  {23.2.1 (defaults/linux-64) -> 23.3.2 (conda-forge/noarch)}
     plotly  {5.17.0 (conda-forge/noarch) -> 5.18.0 (conda-forge/noarch)}
     protobuf  {3.20.3 (conda-forge/linux-64) -> 4.24.4 (conda-forge/linux-64)}
     psutil  {5.9.5 (conda-forge/linux-64) -> 5.9.7 (conda-forge/linux-64)}
     pyasn1  {0.5.0 (conda-forge/noarch) -> 0.5.1 (conda-forge/noarch)}
     pydantic  {1.10.13 (conda-forge/linux-64) -> 1.10.13 (conda-forge/linux-64)}
     pyopenssl  {23.2.0 (conda-forge/noarch) -> 23.3.0 (conda-forge/noarch)}
     python  {3.11.5 (defaults/linux-64) -> 3.11.7 (conda-forge/linux-64)}
     python-tzdata  {2023.3 (conda-forge/noarch) -> 2023.4 (conda-forge/noarch)}
     python_abi  {3.11 (conda-forge/linux-64) -> 3.11 (conda-forge/linux-64)}
     readline  {8.2 (defaults/linux-64) -> 8.2 (conda-forge/linux-64)}
     regex  {2023.10.3 (conda-forge/linux-64) -> 2023.12.25 (conda-forge/linux-64)}
     scikit-learn  {1.3.1 (conda-forge/linux-64) -> 1.3.2 (conda-forge/linux-64)}
     scipy  {1.11.3 (conda-forge/linux-64) -> 1.11.4 (conda-forge/linux-64)}
     sentry-sdk  {1.32.0 (conda-forge/noarch) -> 1.39.1 (conda-forge/noarch)}
     setuptools  {68.0.0 (defaults/linux-64) -> 69.0.3 (conda-forge/noarch)}
     smmap  {3.0.5 (conda-forge/noarch) -> 5.0.0 (conda-forge/noarch)}
     sqlalchemy  {2.0.21 (conda-forge/linux-64) -> 2.0.25 (conda-forge/linux-64)}
     tiktoken  {0.5.1 (conda-forge/linux-64) -> 0.5.2 (conda-forge/linux-64)}
     tk  {8.6.12 (defaults/linux-64) -> 8.6.13 (conda-forge/linux-64)}
     tree_sitter  {0.20.2 (conda-forge/linux-64) -> 0.20.3 (conda-forge/linux-64)}
     tree_sitter_languages  {1.7.0 (conda-forge/linux-64) -> 1.9.1 (conda-forge/linux-64)}
     typing-extensions  {4.8.0 (conda-forge/noarch) -> 4.9.0 (conda-forge/noarch)}
     typing_extensions  {4.8.0 (conda-forge/noarch) -> 4.9.0 (conda-forge/noarch)}
     tzdata  {2023c (defaults/noarch) -> 2023d (conda-forge/noarch)}
     urllib3  {1.26.17 (conda-forge/noarch) -> 1.26.18 (conda-forge/noarch)}
     werkzeug  {2.2.3 (defaults/linux-64) -> 3.0.1 (conda-forge/noarch)}
     wheel  {0.41.2 (defaults/linux-64) -> 0.42.0 (conda-forge/noarch)}
     xz  {5.4.2 (defaults/linux-64) -> 5.2.6 (conda-forge/linux-64)}
     yarl  {1.9.2 (conda-forge/linux-64) -> 1.9.3 (conda-forge/linux-64)}
     zstd  {1.5.5 (defaults/linux-64) -> 1.5.5 (conda-forge/linux-64)}
    +blinker-1.7.0 (conda-forge/noarch)
    +importlib-metadata-7.0.1 (conda-forge/noarch)
    +libabseil-20230802.1 (conda-forge/linux-64)
    +libexpat-2.5.0 (conda-forge/linux-64)
    +libgomp-13.2.0 (conda-forge/linux-64)
    +libjpeg-turbo-3.0.0 (conda-forge/linux-64)
    +libnsl-2.0.1 (conda-forge/linux-64)
    +libsqlite-3.44.2 (conda-forge/linux-64)
    +libxcb-1.15 (conda-forge/linux-64)
    +libxcrypt-4.4.36 (conda-forge/linux-64)
    +libzlib-1.2.13 (conda-forge/linux-64)
    +openjpeg-2.5.0 (conda-forge/linux-64)
    +pthread-stubs-0.4 (conda-forge/linux-64)
    +xorg-libxau-1.0.11 (conda-forge/linux-64)
    +xorg-libxdmcp-1.1.3 (conda-forge/linux-64)
    +zipp-3.17.0 (conda-forge/noarch)

